name: Test with Prioritized Failed Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      # Download previous test report from cache
      - name: Download previous test report artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: test-report
          path: previous-test-report
        continue-on-error: true  # If there's no previous artifact, don't fail

      # Parse the previous HTML report for failed tests
      - name: Extract failed tests from previous run
        id: extract-failed-tests
        run: |
          python parse_html_report.py previous-test-report/report.html failed_tests.txt || echo "No previous failures"
      
      # Save extracted failed tests as an artifact for debugging
      - name: Upload failed tests list
        if: success()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: failed-tests
          path: failed_tests.txt
        continue-on-error: true

      # Run prioritized failed tests (if any)
      - name: Run prioritized failed tests
        if: success() && hashFiles('failed_tests.txt') != ''
        run: |
          pytest --html=test-reports/priority-report.html --self-contained-html --maxfail=1 $(cat failed_tests.txt)

      # Run all tests and generate a full HTML report
      - name: Run all tests and generate full HTML report
        run: |
          pytest --html=test-reports/report.html --self-contained-html

      # Upload the full test report
      - name: Upload test report artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: test-report
          path: test-reports/*.html
