name: Run Tests, Save, and Retrieve Results

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read  # Allows GitHub Actions to fetch artifacts

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-json-report jq

      - name: Get PR ID
        if: github.event_name == 'pull_request'
        run: echo "PR_ID=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set Default Folder for Non-PR Runs
        if: github.event_name != 'pull_request'
        run: echo "PR_ID=main" >> $GITHUB_ENV

      - name: Retrieve Previous Artifacts (If Exists)
        run: |
          echo "Fetching previous test results for PR ${PR_ID}..."

          # Fetch list of artifacts from GitHub API
          ARTIFACTS_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")

          # Check if API call failed (403 error or empty response)
          if echo "$ARTIFACTS_RESPONSE" | grep -q '"message": "Resource not accessible by integration"'; then
            echo "GitHub API access denied (403 Forbidden). Skipping artifact retrieval."
            exit 0  # Do not fail the workflow
          fi

          echo "Raw API Response: $ARTIFACTS_RESPONSE"

          # Extract the latest artifact URL using jq
          ARTIFACT_URL=$(echo "$ARTIFACTS_RESPONSE" | jq -r --arg PR "pr-${PR_ID}-test-results" \
            '[.artifacts[] | select(.name==$PR)] | sort_by(.created_at) | reverse | .[0].archive_download_url')

          echo "Extracted Latest Artifact URL: $ARTIFACT_URL"

          if [[ -n "$ARTIFACT_URL" && "$ARTIFACT_URL" != "null" ]]; then
            echo "Latest artifact found. Downloading..."
            mkdir -p artifacts/pr-${PR_ID}
            curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -o artifacts/pr-${PR_ID}/test-results.zip "$ARTIFACT_URL"
            unzip -o artifacts/pr-${PR_ID}/test-results.zip -d artifacts/pr-${PR_ID}

            # Print the contents of previous test results
            echo "======================================="
            echo "Previous Test Results for PR-${PR_ID}:"
            cat artifacts/pr-${PR_ID}/test_results.json || echo "No previous test results found."
            echo "======================================="

          else
            echo "No previous test results found for PR-${PR_ID}. Running fresh tests."
          fi

      - name: Extract Failed and Passed Tests from Previous Run
        run: |
          PREV_RESULTS="artifacts/pr-${PR_ID}/test_results.json"
          FAILED_TESTS_FILE="artifacts/pr-${PR_ID}/failed_tests.txt"
          ALL_TESTS_FILE="artifacts/pr-${PR_ID}/all_tests.txt"
          REMAINING_TESTS_FILE="artifacts/pr-${PR_ID}/remaining_tests.txt"

          # Collect all test cases in the project
          pytest --collect-only --quiet | grep "::" > $ALL_TESTS_FILE

          if [[ -f "$PREV_RESULTS" ]]; then
            echo "Extracting failed test cases from previous run..."
            cat $PREV_RESULTS | jq -r '.tests | map(select(.outcome == "failed")) | .[].nodeid' > $FAILED_TESTS_FILE
          fi

          if [[ -s "$FAILED_TESTS_FILE" ]]; then
            echo "Failed tests from the previous run:"
            cat $FAILED_TESTS_FILE
          else
            echo "No previously failed tests found."
          fi

      - name: Run Previously Failed Tests First
        run: |
          FAILED_TESTS_FILE="artifacts/pr-${PR_ID}/failed_tests.txt"

          if [[ -s "$FAILED_TESTS_FILE" ]]; then
            echo "Rerunning previously failed tests first..."
            pytest --tb=short --json-report --json-report-file=artifacts/pr-${PR_ID}/temp_test_results.json $(cat $FAILED_TESTS_FILE) || true
          else
            echo "No previously failed tests found."
          fi

      - name: Check If Any Tests Failed Again
        run: |
          TEMP_RESULTS="artifacts/pr-${PR_ID}/temp_test_results.json"
          FAILED_AGAIN_FILE="artifacts/pr-${PR_ID}/failed_again.txt"

          if [[ -f "$TEMP_RESULTS" ]]; then
            echo "Checking if any tests failed again..."
            cat $TEMP_RESULTS | jq -r '.tests | map(select(.outcome == "failed")) | .[].nodeid' > $FAILED_AGAIN_FILE
          fi

          if [[ -s "$FAILED_AGAIN_FILE" ]]; then
            echo "Some tests failed again. Stopping execution."
            exit 1  # Fail workflow if tests fail again
          fi

      - name: Identify Remaining Untested Test Cases
        run: |
          FAILED_TESTS_FILE="artifacts/pr-${PR_ID}/failed_tests.txt"
          ALL_TESTS_FILE="artifacts/pr-${PR_ID}/all_tests.txt"
          REMAINING_TESTS_FILE="artifacts/pr-${PR_ID}/remaining_tests.txt"

          echo "Finding remaining tests to run..."
          grep -v -F -f $FAILED_TESTS_FILE $ALL_TESTS_FILE > $REMAINING_TESTS_FILE || true

          if [[ -s "$REMAINING_TESTS_FILE" ]]; then
            echo "Remaining tests to run:"
            cat $REMAINING_TESTS_FILE
          else
            echo "No remaining tests to run."
          fi

      - name: Run Remaining Test Cases
        run: |
          REMAINING_TESTS_FILE="artifacts/pr-${PR_ID}/remaining_tests.txt"

          if [[ -s "$REMAINING_TESTS_FILE" ]]; then
            echo "Running remaining test cases..."
            pytest --tb=short --json-report --json-report-file=artifacts/pr-${PR_ID}/test_results.json $(cat $REMAINING_TESTS_FILE) || true
          else
            echo "No remaining tests to run."
          fi

      - name: Upload New Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ env.PR_ID }}-test-results
          path: artifacts/pr-${{ env.PR_ID }}/test_results.json

  retrieve-results:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Get PR ID
        if: github.event_name == 'pull_request'
        run: echo "PR_ID=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set Default Folder for Non-PR Runs
        if: github.event_name != 'pull_request'
        run: echo "PR_ID=main" >> $GITHUB_ENV

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: pr-${{ env.PR_ID }}-test-results
          path: retrieved-results

      - name: Display Retrieved Test Results
        run: |
          echo "======================================="
          echo "Retrieved Test Results from PR ${PR_ID}:"
          cat retrieved-results/test_results.json
          echo "======================================="
