name: Run, Save, and Retrieve Test Results

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-json-report

      - name: Run Tests and Save Results
        run: |
          pytest --tb=short --json-report --json-report-file=test_results.json || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.json

  retrieve-results:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: retrieved-results

      - name: Format and Display Test Results
        run: |
          import json

          # Load the JSON test results
          with open('retrieved-results/test_results.json', 'r') as file:
              data = json.load(file)

          # Extract summary
          summary = data.get("summary", {})
          passed = summary.get("passed", 0)
          failed = summary.get("failed", 0)
          total = summary.get("total", 0)

          # Print Summary
          print("\n📊 TEST RESULTS SUMMARY 📊")
          print(f"✅ Passed: {passed}  ❌ Failed: {failed}  🔢 Total: {total}\n")

          # Print Failed Tests
          if failed > 0:
              print("❌ FAILED TEST DETAILS:")
              print("| Test Case | File | Line No. | Error |")
              print("|-----------|------|---------|-------|")

              for test in data.get("tests", []):
                  if test["outcome"] == "failed":
                      error_message = test["call"]["crash"]["message"]
                      print(f"| {test['nodeid']} | {test['keywords'][1]} | {test['lineno']} | {error_message} |")

          # Print Passed Tests
          print("\n✅ PASSED TESTS:")
          for test in data.get("tests", []):
              if test["outcome"] == "passed":
                  print(f"- {test['nodeid']}")

        shell: python
