name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/smart-test-runner.yml
    with:
      python-version: '3.10'
      test-command: 'pytest'
      test-args: '--tb=short --json-report'
      fail-on-error: true