name: Run Tests, Save, and Retrieve Results

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-json-report

      - name: Run Tests and Save Results
        run: |
          pytest --tb=short --json-report --json-report-file=${{ github.event.number }}/test_results.json || true

      - name: Create Directory
        run: |
          mkdir -p "${{ github.event.number }}"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.event.number }}/test_results.json

  retrieve-results:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ${{ github.event.number }}/retrieved-results

      - name: Display Retrieved Test Results
        run: |
          echo "Retrieved Test Results:"
          cat ${{ github.event.number }}/retrieved-results/test_results.json
